/**
 * Recommendation engine types.
 *
 * Layer 1: Rule-based filtering (hard filters from user context)
 * Layer 2: Score-based ranking (composite score per user context)
 * Layer 3: LLM explanation (generates human-readable rationale)
 */

/** User types that drive persona-specific filtering. */
export type UserType = "individual" | "freelancer" | "founder" | "team";

/** Solution areas that tools can be mapped to. */
export type SolutionArea =
  | "revenue"
  | "cost-reduction"
  | "content"
  | "advertising"
  | "ecommerce"
  | "customer-support"
  | "operations"
  | "development"
  | "design"
  | "seo";

/** Budget tiers for price-based filtering. */
export type BudgetTier = "free-only" | "low" | "mid" | "best";

/** Team structure options. */
export type TeamStructure = "solo" | "small" | "growing" | "established";

/** User context captured during onboarding. */
export interface UserContext {
  userType: UserType;
  businessDescription: string;
  goals: SolutionArea[];
  teamStructure: TeamStructure;
  budget: BudgetTier;
  freeText?: string;
}

/** A single tool recommendation with scoring context. */
export interface RecommendedTool {
  toolId: string;
  compositeScore: number;
  primaryRole: "best-fit" | "free-alt" | "power-alt";
  matchedSolutionAreas: SolutionArea[];
  /** Short human-readable rationale — generated by LLM layer. */
  rationale?: string;
}

/** Full recommendation result returned to the results page. */
export interface RecommendationResult {
  userId?: string;
  sessionId: string;
  context: UserContext;
  diagnosis: string;
  solutionAreas: SolutionArea[];
  recommendations: RecommendedTool[];
  generatedAt: string;
}
