/**
 * Ranking service — the single read interface for all ranking data.
 *
 * TODAY:  reads from /data/rankings/*.json files (computed by the engine)
 * FUTURE: swap the JSON file reads for Prisma queries without changing any
 *         calling page/component code.
 *
 * The JSON files are regenerated by calling computeAllRankings() via the
 * admin refresh endpoint: POST /api/admin/rankings/refresh
 */

import { computeTop10Rankings, getAvailableCategories } from "./engine";
import { getTools } from "@/lib/tools/store";
import type { RankingSnapshot, RankingCardData, RankingPeriod } from "./types";

/* ─── In-process cache ───────────────────────────────────────────────────── */
// Computed once per process lifetime (or until refresh is called).
// When switching to Prisma, remove this and query the DB directly.

let _cache: RankingSnapshot[] | null = null;

function getCache(): RankingSnapshot[] {
  if (!_cache) {
    _cache = computeTop10Rankings();
  }
  return _cache;
}

/** Call this after admin refresh to bust the in-process cache */
export function bustRankingCache(): void {
  _cache = null;
}

/* ─── Snapshot lookup ────────────────────────────────────────────────────── */

export function getOverallRanking(period: RankingPeriod): RankingSnapshot | null {
  return (
    getCache().find((s) => s.type === "overall" && s.period === period) ?? null
  );
}

export function getCategoryRanking(
  period: RankingPeriod,
  category: string
): RankingSnapshot | null {
  return (
    getCache().find(
      (s) => s.type === "category" && s.period === period && s.category === category
    ) ?? null
  );
}

export function getHiddenGemsRanking(): RankingSnapshot | null {
  return getCache().find((s) => s.type === "hidden-gems") ?? null;
}

export function getAllCategories(): string[] {
  return getAvailableCategories();
}

/* ─── Snapshot → UI cards ────────────────────────────────────────────────── */

function toolForSlug(slug: string) {
  return getTools().find((t) => t.slug === slug);
}

export function snapshotToCards(snapshot: RankingSnapshot): RankingCardData[] {
  return snapshot.entries
    .map((entry) => {
      const tool = toolForSlug(entry.toolSlug);
      if (!tool) return null;

      const gemReason = snapshot.type === "hidden-gems" ? entry.contextNote ?? undefined : undefined;

      const card: RankingCardData = {
        rank:             entry.rank,
        slug:             tool.slug,
        name:             tool.name,
        tagline:          tool.tagline,
        websiteUrl:       tool.websiteUrl,
        strongestUseCase: tool.strongSignals[0] ?? tool.tagline,
        category:         tool.category,
        signals:          tool.strongSignals.slice(0, 3),
        compositeScore:   entry.score,
        hasFree:          tool.hasFree,
        isSponsored:      entry.isSponsored,
        contextNote:      snapshot.type !== "hidden-gems" ? entry.contextNote : null,
      };
      if (gemReason !== undefined) card.hiddenGemReason = gemReason;
      return card;
    })
    .filter((c): c is RankingCardData => c !== null);
}

/* ─── Convenience: cards ready for UI ───────────────────────────────────── */

export function getOverallCards(period: RankingPeriod, limit = 10): RankingCardData[] {
  const snap = getOverallRanking(period);
  if (!snap) return [];
  return snapshotToCards(snap).slice(0, limit);
}

export function getCategoryCards(
  period: RankingPeriod,
  category: string,
  limit = 10
): RankingCardData[] {
  const snap = getCategoryRanking(period, category);
  if (!snap) return [];
  return snapshotToCards(snap).slice(0, limit);
}

export function getHiddenGemCards(limit = 10): RankingCardData[] {
  const snap = getHiddenGemsRanking();
  if (!snap) return [];
  return snapshotToCards(snap).slice(0, limit);
}

/** Homepage top 5 — always weekly overall */
export function getHomepageTop5(): RankingCardData[] {
  return getOverallCards("weekly", 5);
}

/** Last computation timestamp */
export function getLastComputedAt(): string {
  const snaps = getCache();
  if (snaps.length === 0) return new Date().toISOString();
  return snaps[0].generatedAt;
}
